version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: fila_digital
      MYSQL_USER: fila_digital
      MYSQL_PASSWORD: pr342fi9f3q9238ur23
      MYSQL_ROOT_PASSWORD: pr342fi9f3q9238ur23
    volumes:
      # Initial script
      - ./init.sql:/docker-entrypoint-initdb.d/mysql-init.sql 
    ports:
      - "3306:3306"
    restart: always
    
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    links:
      - mysql